version: "3.9"

services:
  aggregator:
    build: ./aggregator
    image: uts-aggregator:latest
    environment:
      - DATABASE_URL=postgresql://user:pass@storage:5432/db
      - BROKER_URL=redis://broker:6379
      - WORKERS=4
    depends_on:
      - storage
      - broker
    ports:
      - "8080:8080"
    volumes:
      # HAPUS pg_data DARI SINI
      - ./aggregator:/app  # Ini bagus supaya kalau edit code langsung update (Hot reload)
    networks:
      - internal_net

  publisher:
    build: ./publisher
    image: uts-publisher:latest
    depends_on:
      - aggregator
    environment:
      - TARGET_URL=http://aggregator:8080/publish
    networks:
      - internal_net

  storage:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - pg_data:/var/lib/postgresql/data # <<< INI BENAR (Hanya di sini)
    networks:
      - internal_net

  broker:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - broker_data:/data
    networks:
      - internal_net

networks:
  internal_net:

volumes:
  pg_data:
  broker_data: